# Generated by Django 3.0.5 on 2020-05-09 03:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0002_account_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='queryjob',
            name='account_key',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='queryjob',
            name='id',
            field=models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
