# Generated by Django 3.0.5 on 2020-05-09 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0003_auto_20200509_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='creater',
            field=models.CharField(default='', max_length=36),
        ),
        migrations.AddField(
            model_name='account',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='account',
            name='updater',
            field=models.CharField(default='', max_length=36),
        ),
        migrations.AddField(
            model_name='account',
            name='updatetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='queryjob',
            name='creater',
            field=models.CharField(default='', max_length=36),
        ),
        migrations.AddField(
            model_name='queryjob',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='queryjob',
            name='updater',
            field=models.CharField(default='', max_length=36),
        ),
        migrations.AddField(
            model_name='queryjob',
            name='updatetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
