# Generated by Django 3.0.5 on 2020-05-09 12:24

from django.db import migrations, models
import libs.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0004_auto_20200509_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitUser',
            fields=[
                ('id', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('job_key', models.CharField(max_length=36)),
                ('account_key', models.CharField(max_length=36)),
            ],
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
        migrations.AddField(
            model_name='queryjob',
            name='state',
            field=models.IntegerField(choices=[('0', 'new'), ('1', 'start'), ('2', 'running'), ('3', 'block'), ('4', 'end')], default=0),
        ),
    ]
