# Generated by Django 3.0.5 on 2020-05-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0005_auto_20200509_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password_ticket',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='queryjob',
            name='state',
            field=models.IntegerField(choices=[(0, 'new'), (1, 'start'), (2, 'running'), (3, 'block'), (4, 'end')], default=0),
        ),
    ]
