# Generated by Django 3.0.5 on 2020-05-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0006_auto_20200519_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queryjob',
            old_name='stations',
            new_name='arrive_station',
        ),
        migrations.RenameField(
            model_name='queryjob',
            old_name='except_train_numbers',
            new_name='train_number',
        ),
        migrations.RemoveField(
            model_name='queryjob',
            name='peroid',
        ),
        migrations.RemoveField(
            model_name='queryjob',
            name='train_numbers',
        ),
        migrations.AddField(
            model_name='queryjob',
            name='left_station',
            field=models.CharField(default='', max_length=100),
        ),
    ]
