# Generated by Django 3.0.5 on 2020-05-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0007_auto_20200521_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queryjob',
            name='members',
        ),
        migrations.AddField(
            model_name='queryjob',
            name='passengers',
            field=models.CharField(default='2', max_length=256),
        ),
    ]
