# Generated by Django 3.0.5 on 2020-05-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0008_auto_20200521_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryjob',
            name='passengers',
            field=models.CharField(default='', max_length=256),
        ),
    ]
