# Generated by Django 3.0.5 on 2020-05-24 12:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0009_auto_20200521_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queryjob',
            name='account_key',
        ),
        migrations.RemoveField(
            model_name='queryjob',
            name='allow_less_member',
        ),
        migrations.RemoveField(
            model_name='queryjob',
            name='name',
        ),
        migrations.RemoveField(
            model_name='queryjob',
            name='passengers',
        ),
        migrations.RemoveField(
            model_name='queryjob',
            name='seats',
        ),
        migrations.AddField(
            model_name='waituser',
            name='allow_less_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waituser',
            name='arrive_station',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='waituser',
            name='creater',
            field=models.CharField(default='', max_length=36),
        ),
        migrations.AddField(
            model_name='waituser',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='waituser',
            name='left_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 24, 20, 15, 49, 7552)),
        ),
        migrations.AddField(
            model_name='waituser',
            name='left_station',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='waituser',
            name='passengers',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='waituser',
            name='seats',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='waituser',
            name='state',
            field=models.IntegerField(choices=[(0, 'new'), (1, 'start'), (2, 'running'), (3, 'block'), (4, 'end')], default=0),
        ),
        migrations.AddField(
            model_name='waituser',
            name='train_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='waituser',
            name='updater',
            field=models.CharField(default='', max_length=36),
        ),
        migrations.AddField(
            model_name='waituser',
            name='updatetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='waituser',
            name='job_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_admin.QueryJob'),
        ),
    ]
