# Generated by Django 3.0.5 on 2020-05-24 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0010_auto_20200524_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='waituser',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='waituser',
            name='left_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 24, 20, 19, 2, 802632)),
        ),
    ]
