# Generated by Django 3.0.5 on 2020-05-25 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0012_auto_20200524_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waituser',
            name='left_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 25, 17, 55, 38, 402565)),
        ),
    ]
