# Generated by Django 3.0.5 on 2020-05-26 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0013_auto_20200525_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='createtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='queryjob',
            name='createtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='waituser',
            name='createtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='waituser',
            name='left_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
