# Generated by Django 3.0.5 on 2020-05-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0014_auto_20200526_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryjob',
            name='count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='waituser',
            name='state',
            field=models.IntegerField(choices=[(0, 'RUNNING'), (1, 'END')], default=0),
        ),
    ]
