# Generated by Django 3.0.5 on 2020-06-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0015_auto_20200527_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waituser',
            name='state',
            field=models.IntegerField(choices=[(0, 'RUNNING'), (1, 'ORDERING'), (2, 'END')], default=0),
        ),
    ]
