# Generated by Django 3.0.5 on 2020-06-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0017_auto_20200612_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waituser',
            name='reason',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='waituser',
            name='result',
            field=models.BooleanField(default=False),
        ),
    ]
