# Generated by Django 3.0.5 on 2020-06-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0018_auto_20200617_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='waituser',
            name='uid',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='waituser',
            name='reason',
            field=models.CharField(default='未开始', max_length=50),
        ),
    ]
